trigger:
- dev

parameters:
- name: environment
  type: string
  default: dev
  values:
    - dev
    - prod

variables:
- group: WildCard-Infra-Variables
- name: PULUMI_STACK
  value: ${{ parameters.environment }}

stages:

# =========================================================
# SETUP
# =========================================================
- stage: Setup
  jobs:
  - job: install
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: "20.x"

    - script: |
        curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
        infracost --version
      displayName: Install Infracost


# =========================================================
# PLAN
# =========================================================
- stage: Plan
  dependsOn: Setup
  jobs:
  - job: preview
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Pulumi@0
      displayName: Pulumi Preview
      inputs:
        command: preview
        stack: $(PULUMI_STACK)
        args: --diff --json > preview.json
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)

    - script: |
        infracost breakdown --path preview.json
      displayName: Cost Estimate


# =========================================================
# APPLY
# =========================================================
- stage: Apply
  dependsOn: Plan

  jobs:
  - deployment: pulumi_apply
    displayName: "Manual Apply"
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:

          - task: Pulumi@0
            displayName: Pulumi Up
            inputs:
              command: up
              stack: $(PULUMI_STACK)
              args: --yes
            env:
              PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)